git_repos = [
  "~/.doom.d",
  "~/.emacs.d"
]

disable = ["emacs", "go"]

[commands]
"Doom refresh" = "cd ~/.doom.d; ~/.emacs.d/bin/doom refresh"
"Doom update" = "cd ~/.doom.d; ~/.emacs.d/bin/doom update"
