disable = ["emacs", "go"]

[git]
repos = [
  "~/.doom.d",
  "~/.emacs.d"
]

[commands]
"Doom sync" = "cd ~/.doom.d; ~/.emacs.d/bin/doom sync"
"Doom update" = "cd ~/.doom.d; ~/.emacs.d/bin/doom update"
