disable = ["emacs", "go", "snap"]

[git]
repos = [
  "~/.doom.d",
  "~/.emacs.d"
]
arguments = "--rebase --autostash"

[commands]
"Doom sync" = "cd ~/.doom.d; ~/.emacs.d/bin/doom sync"
"Doom upgrade" = "cd ~/.doom.d; ~/.emacs.d/bin/doom upgrade"
